name: Create Release

on:
  workflow_dispatch:

env:
  dotnet-ver: "8.x"

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4^
      
    - name: Cache .NET Runtime
      uses: actions/cache@v4^
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "C:/Users/runneradmin/AppData/Local/Microsoft/dotnet/"
        # An explicit key for restoring and saving the cache
        key: "${{ runner.os }}-${{ runner.arch }}-${{ env.dotnet-ver }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4^
      with:
        dotnet-version: ${{ env.dotnet-ver }}
    
    - name: Build
      run: dotnet publish -p:PublishProfile=ContainedWin64

    - name: Get version
      id: set_version
      run: echo "version=$(./ConsoleDownloaderClient/bin/**/*.exe version)" >> $GITHUB_OUTPUT
    
    - name: Create release
      uses: softprops/action-gh-release@v2^
      with:
        tag_name: steps.set_version.outputs.version
        path: "**/publish/*.exe"
