name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Cache
      uses: actions/cache@v3.0.7
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "**/dotnet/"
        # An explicit key for restoring and saving the cache
        key: "${{ RUNNER_OS }}-${{ RUNNER_ARCH }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet publish -p:PublishProfile=FolderProfile --no-restore 
      
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ConsoleDownloader
        path: "**/publish/*.exe"
